apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
  namespace: argocd
sepc:
  replicas: 7
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
        - name: mydepcom
          image: shaikmustafa/paytm:movie
          ports:
            -  containerPort: 80

